buildType: MAVEN

buildDeps:
  - hs-build-tools
  - maven3

buildpack:
  name: Blazar-Buildpack-RPM
  branch: follow-maven-dir

env:
  PLATFORMS: "amd64 arm64"
  # Don't use the buildpack to build and upload RPMs for us
  DISABLE_CENTOS_6_RPMS: "true"
  ENABLE_CENTOS_8_RPMS: "true"

  # The entry point script for the rpm build
  RPM_BUILD_COMMAND: "./build.sh"
  RPMS_OUTPUT_DIR: "$WORKSPACE/generated_rpms"
  BUILD_CONTAINER_IMAGE_CENTOS_8: "docker.hubteam.com/apache-hadoop-build-container/remove-wailmer-arm64/apache-hadoop-build-container:latest"
  WORKSPACE_WRITEABLE: "true"

stepActivation:
  uploadRpms:
    branchRegexes: [.*]
