import java.text.SimpleDateFormat
import java.util.Date
import java.util.TimeZone

plugins {
    java
}

group = "com.hadoop.gplcompression"
version = (findProperty("version") as String?)
    ?.takeIf { it.isNotBlank() && it != "unspecified" }
    ?: file("version").readText().trim()

val hadoopVersion = "3.3.1"

repositories {
    mavenCentral()
}

dependencies {
    // Hadoop is provided by the runtime environment (Hadoop's own classpath).
    compileOnly("org.apache.hadoop:hadoop-common:$hadoopVersion")
    compileOnly("org.apache.hadoop:hadoop-mapreduce-client-core:$hadoopVersion")
    implementation("commons-logging:commons-logging:1.2")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.apache.hadoop:hadoop-common:$hadoopVersion")
    testImplementation("org.apache.hadoop:hadoop-mapreduce-client-core:$hadoopVersion")
}

// Directory where scripts/build-native.sh writes the per-platform native libs.
// In CI's packaging job this is populated by downloading every platform's
// artifact; locally it holds just the host platform.
val nativeResourcesDir = layout.buildDirectory.dir("native-resources")
val nativeHeadersDir = layout.buildDirectory.dir("native-headers")
val generatedResourcesDir = layout.buildDirectory.dir("generated-resources")

// Emit JNI headers so the native build can compile against them.
tasks.compileJava {
    options.release.set(8)
    options.headerOutputDirectory.set(nativeHeadersDir)
}

tasks.compileTestJava {
    options.release.set(8)
}

sourceSets {
    main {
        resources {
            srcDir(nativeResourcesDir)
            srcDir(generatedResourcesDir)
        }
    }
}

// Reproduces the build metadata LzoCodec reads from the classpath.
val generateBuildProperties = tasks.register("generateBuildProperties") {
    val outputFile = generatedResourcesDir.get().file("hadoop-lzo-build.properties").asFile
    val projectVersion = version.toString()
    inputs.property("version", projectVersion)
    outputs.file(outputFile)
    doLast {
        fun capture(vararg cmd: String): String = try {
            val proc = ProcessBuilder(*cmd).redirectErrorStream(true).start()
            val text = proc.inputStream.bufferedReader().readText().trim()
            proc.waitFor()
            text
        } catch (e: Exception) {
            "Unknown"
        }

        val revision = System.getenv("BUILD_REVISION")
            ?: capture("git", "rev-parse", "HEAD").ifBlank { "Unknown build revision" }
        val author = capture("whoami")
        val buildOs = capture("uname", "-a")
        val df = SimpleDateFormat("MM/dd/yyyy hh:mm aa")
        df.timeZone = TimeZone.getTimeZone("GMT")
        val buildTime = df.format(Date())

        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            buildString {
                appendLine("#This file is automatically generated - DO NOT EDIT")
                appendLine("build_time=$buildTime")
                appendLine("build_revision=$revision")
                appendLine("build_author=$author")
                appendLine("build_version=$projectVersion")
                appendLine("build_os=$buildOs")
            }
        )
    }
}

// Builds the native library for the host platform into nativeResourcesDir.
// Intentionally NOT wired into `jar` so the packaging job can assemble a JAR
// purely from downloaded artifacts without invoking a compiler.
val buildNative = tasks.register<Exec>("buildNative") {
    dependsOn(tasks.compileJava)
    workingDir = projectDir
    environment("HEADERS_DIR", nativeHeadersDir.get().asFile.absolutePath)
    environment("OUTPUT_ROOT", nativeResourcesDir.get().asFile.absolutePath)
    commandLine("./scripts/build-native.sh")
}

tasks.processResources {
    dependsOn(generateBuildProperties)
}

tasks.test {
    dependsOn(buildNative)
    // The native lib is loaded from the classpath by GPLNativeCodeLoader, but
    // set java.library.path too for parity with the historical build.
    systemProperty(
        "java.library.path",
        nativeResourcesDir.get().asFile.walkTopDown()
            .filter { it.isDirectory && it.name == "lib" }
            .joinToString(File.pathSeparator) { it.absolutePath }
    )
    systemProperty("test.build.data", layout.buildDirectory.dir("resources/test/data").get().asFile.absolutePath)
    systemProperty("hadoop.log.dir", layout.buildDirectory.dir("test-logs").get().asFile.absolutePath)
    systemProperty("test.src.dir", file("src/test/java").absolutePath)
    systemProperty("hadoop.policy.file", "hadoop-policy.xml")
    // Native handles cannot be shared across forks.
    setForkEvery(1L)
}

tasks.processTestResources {
    mustRunAfter(buildNative)
}

tasks.jar {
    archiveBaseName.set("hadoop-lzo")
    manifest {
        attributes(
            "Implementation-Title" to "hadoop-lzo",
            "Implementation-Version" to project.version
        )
    }
}
