#!/usr/bin/env bash
#
# Builds libgplcompression for the host platform by compiling the JNI bindings
# and the full LZO library sources into a single shared object, and drops it
# where the JAR expects it:
#
#   ${OUTPUT_ROOT}/native/<Java-os.name>-<Java-os.arch>-64/lib/libgplcompression.{so,dylib}
#
# The layout and library name match what GPLNativeCodeLoader unpacks at runtime.
# LZO is compiled in directly (no separate archive, no configure/make/libtool),
# so the result is self-contained and depends only on the system C library.
#
# Environment:
#   JAVA_HOME     required, provides jni.h
#   HEADERS_DIR   JNI headers generated by `gradlew compileJava`
#                 (default: build/native-headers)
#   OUTPUT_ROOT   where the native/ resource tree is written
#                 (default: build/native-resources)
#   PLATFORM_DIR  override the auto-detected <os>-<arch>-64 directory name
#   LZO_TARBALL   lzo source tarball (default: provided/lzo-2.10.tar.gz)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

: "${JAVA_HOME:?JAVA_HOME must be set}"
HEADERS_DIR="${HEADERS_DIR:-build/native-headers}"
OUTPUT_ROOT="${OUTPUT_ROOT:-build/native-resources}"
LZO_TARBALL="${LZO_TARBALL:-provided/lzo-2.10.tar.gz}"

if [ ! -d "$HEADERS_DIR" ]; then
  echo "JNI headers not found in $HEADERS_DIR. Run './gradlew compileJava' first." >&2
  exit 1
fi

uname_s="$(uname -s)"
uname_m="$(uname -m)"

case "$uname_s" in
  Linux)
    os_name="Linux"; jni_os="linux"; lib_ext="so" ;;
  Darwin)
    os_name="Mac_OS_X"; jni_os="darwin"; lib_ext="dylib" ;;
  *)
    echo "Unsupported OS: $uname_s" >&2; exit 1 ;;
esac

# Map machine arch to the value Java reports in os.arch on this OS.
case "$uname_s:$uname_m" in
  Linux:x86_64)         java_arch="amd64" ;;
  Linux:aarch64|Linux:arm64) java_arch="aarch64" ;;
  Darwin:x86_64)        java_arch="x86_64" ;;
  Darwin:arm64|Darwin:aarch64) java_arch="aarch64" ;;
  *) echo "Unsupported arch: $uname_m on $uname_s" >&2; exit 1 ;;
esac

PLATFORM_DIR="${PLATFORM_DIR:-${os_name}-${java_arch}-64}"

BUILD_DIR="build/native-build"
OUT_LIB_DIR="$OUTPUT_ROOT/native/$PLATFORM_DIR/lib"

echo "==> Building libgplcompression for $PLATFORM_DIR"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR" "$OUT_LIB_DIR"

# Unpack the LZO sources; they are compiled straight into the library below.
tar xf "$LZO_TARBALL" -C "$BUILD_DIR"
LZO_SRC="$(find "$BUILD_DIR" -maxdepth 1 -type d -name 'lzo-*' | head -n1)"

# JNI bindings plus every LZO compressor/decompressor source file. LZO uses its
# own portable feature detection unless LZO_HAVE_CONFIG_H is set, so we simply
# don't define it and skip its autoconf step entirely.
SRCS=(
  src/main/native/impl/lzo/LzoCompressor.c
  src/main/native/impl/lzo/LzoDecompressor.c
)
SRCS+=("$LZO_SRC"/src/*.c)

INCLUDES=(
  "-I${JAVA_HOME}/include"
  "-I${JAVA_HOME}/include/${jni_os}"
  "-I${HEADERS_DIR}"
  "-Isrc/main/native/impl"
  "-I${LZO_SRC}/include"
  "-I${LZO_SRC}/src"
)
OUT="$OUT_LIB_DIR/libgplcompression.$lib_ext"

echo "==> Compiling $((${#SRCS[@]})) source files into $OUT"
if [ "$os_name" = "Linux" ]; then
  ${CC:-gcc} -shared -fPIC -O2 "${INCLUDES[@]}" "${SRCS[@]}" -o "$OUT"
else
  ${CC:-clang} -dynamiclib -fPIC -O2 "${INCLUDES[@]}" "${SRCS[@]}" -o "$OUT"
fi

echo "==> Done: $OUT"
ls -l "$OUT"
